name: CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                cd hngx-stage2-fastapi-book-project &&
                git pull origin main &&
                python3 -m venv venv &&
                source venv/bin/activate &&
                python3 -m pip install --upgrade pip &&
                pip install -r requirements.txt &&
                sudo systemctl daemon-reload &&
                sudo systemctl enable fastapi-app &&
                sudo systemctl restart fastapi-app