name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install flake8 pytest  # Install both Flake8 and pytest

    - name: Check for syntax errors
      run: |
        source venv/bin/activate
        python3 -m py_compile $(find . -name "*.py")

    - name: Auto-format code
      run: |
        source venv/bin/activate
        pip install black isort
        black .
        isort .

    - name: Run flake8 for linting
      run: |
        source venv/bin/activate
        pip install flake8
        flake8 .

    - name: Run pytest
      run: |
        source venv/bin/activate
        pytest
