name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt flake8 pytest black isort

    - name: Check for syntax errors
      run: |
        source venv/bin/activate
        python3 -m py_compile $(find . -name "*.py")

    - name: Run flake8 for linting
      run: |
        source venv/bin/activate
        flake8 . || exit 1

    - name: Test invalid code
      run: |
        source venv/bin/activate
        echo "def invalid_function():" > invalid_code.py
        echo "    return" >> invalid_code.py
        echo "invalid_function(" >> invalid_code.py  # Missing closing parenthesis
        python3 -m py_compile invalid_code.py || exit 1

    - name: Run pytest
      run: |
        source venv/bin/activate
        pytest